name: mobile
description: "A property management mobile application for vendors and revenue officers"
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number is used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.0+0

environment:
  sdk: ">=3.8.1 <4.0.0"

dependency_overrides:
  source_gen: ">=1.5.0 <3.0.0"
  build: ">=2.4.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  go_router: ^16.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  get_it: ^8.2.0
  dartz: ^0.10.1
  faker: ^2.2.0
  injectable: ^2.5.1
  flutter_tabler_icons: ^1.43.0
  async: ^2.13.0
  intl: ^0.20.2
  collection: ^1.19.1
  grpc: ^4.1.0
  styled_widget: ^0.4.1
  uuid: ^4.5.1
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  equatable: ^2.0.7
  protobuf: ^4.1.1
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.9.0
  dotenv: ^4.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  injectable_generator: ^2.7.0
  objectbox_generator: ^4.3.0

flutter_assets:
  assets_path:
    - assets/img/
    - assets/anim/
  output_path: lib/generated
  filename: assets.dart

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/anim/
