on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter pub get
          flutter analyze
          flutter test
          flutter build apk --release
          flutter build appbundle --release
          flutter build ios --release --no-codesign
